name: Pages

on: push
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Gen dummy page
      run: |
        cat > docs/deploy.html <<EOL
        <!doctype html>
        <html>
          <head>
            <title>GitHub Pages deployed!</title>
          </head>
          <body>
            <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
          </body>
        </html>
        EOL

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: github-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}